# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/klu/Desktop/morse_code_encoder/morse_code_encoder.cache/wt [current_project]
set_property parent.project_path C:/Users/klu/Desktop/morse_code_encoder/morse_code_encoder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/klu/Desktop/morse_code_encoder/morse_code_encoder.srcs/sources_1/new/morse_encoder.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/klu/Desktop/morse_code_encoder/morse_code_encoder.srcs/constrs_1/new/PINS.xdc
set_property used_in_implementation false [get_files C:/Users/klu/Desktop/morse_code_encoder/morse_code_encoder.srcs/constrs_1/new/PINS.xdc]


synth_design -top morse_encoder -part xc7a35tcpg236-1


write_checkpoint -force -noxdef morse_encoder.dcp

catch { report_utilization -file morse_encoder_utilization_synth.rpt -pb morse_encoder_utilization_synth.pb }
